const S=window.SITE;
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[['/','Home'],['/product','Product'],['/information','Information'],['/about','About'],['/join','Join'],['/cooperation','Cooperation'],['/members','Members'],['/contact','Contact']];
const paths={bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',list:'M8 6h13M8 12h13M8 18h13M3 6h.1M3 12h.1M3 18h.1',about:'M12 8v.1M12 12v5M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',join:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M20 8v6M17 11h6',right:'M9 18l6-6-6-6',left:'M19 12H5M12 19l-7-7 7-7',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 1 1 0 7.75',link:'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71',mail:'M4 4h16v16H4zM4 6l8 7 8-7',youtube:'M22 12s0-3.5-.45-5.2a2.8 2.8 0 0 0-2-2C17.8 4.3 12 4.3 12 4.3s-5.8 0-7.55.5a2.8 2.8 0 0 0-2 2C2 8.5 2 12 2 12s0 3.5.45 5.2a2.8 2.8 0 0 0 2 2c1.75.5 7.55.5 7.55.5s5.8 0 7.55-.5a2.8 2.8 0 0 0 2-2C22 15.5 22 12 22 12M10 9l5 3-5 3z',x:'M4 4l16 16M20 4 4 20',discord:'M7 7c3-1 7-1 10 0 2 3 3 6 3 10-2 2-4 3-6 3l-1-2M17 7l-1-2M7 7 8-2M7 7c-2 3-3 6-3 10 2 2 4 3 6 3l1-2M7 7l1-2M9 14h.1M15 14h.1'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.grid}"/></svg>`;
const img=(src,alt,cls='')=>src?`<img class="${cls}" src="${E(src)}" alt="${E(alt)}" loading="lazy">`:'';
function art(p){return `<div class="product-art ${E(p.color)}">${img(p.image,p.name,'product-image')}</div>`}
function cards(items){return `<div class="grid">${items.map(p=>`<a class="product floating" href="/product/${E(p.id)}/">${art(p)}<div class="product-copy"><span class="category">${E(p.category)}</span><h3>${E(p.name)}</h3><p>${E(p.description)}</p><div class="product-bottom"><span>サンプルプロジェクト</span><span>詳しく見る ${icon('right')}</span></div></div></a>`).join('')}</div>`}
function rows(items){return items.map(n=>`<a class="news-row" href="/information/${E(n.id)}/"><time>${E(n.date)}</time><span class="badge ${E(n.tag.toLowerCase())}">${E(n.tag)}</span><span class="news-title">${E(n.title)}</span><span class="row-actions">${img(n.image,'','news-thumb')}<span class="arrow">${icon('right')}</span></span></a>`).join('')}
function newsCards(items){return `<div class="news-grid">${items.map(n=>`<a class="news-card floating" href="/information/${E(n.id)}/"><div class="news-card-art">${n.image?img(n.image,'','news-card-image'):`<span>${icon('bell')}</span>`}</div><div class="news-card-copy"><div><time>${E(n.date)}</time><span class="badge ${E(n.tag.toLowerCase())}">${E(n.tag)}</span></div><h2>${E(n.title)}</h2><p>${E(n.body)}</p><span class="news-card-more">詳しく見る ${icon('right')}</span></div></a>`).join('')}</div>`}
function pageHero(title,jp,extra=''){return `<section class="page-hero ${extra}"><div class="wrap"><div class="breadcrumbs"><a href="/">Home</a> / ${E(title)}</div><h1>${E(title)}</h1><p>${E(jp)}</p></div></section>`}
const note='<p class="sample-note">※ 製品・お知らせの内容は、レイアウト確認用のサンプルです。</p>';
function home(){const quick=[['information','Information','お知らせ','pink','bell'],['product','Product','製品紹介','lavender','grid'],['about','About','TowaPCについて','mint','about'],['join','Join','TowaPCに参加する','cream','join']];return `<section class="hero"><img class="hero-background" src="${E(S.hero)}" alt="夕焼けに染まる街並み" fetchpriority="high"><h1>${E(S.headline)}</h1></section><div class="wrap"><section class="intro floating"><h2>What’s “TowaPC”?</h2><p>${E(S.description)}</p><a class="text-link" href="/about/">TowaPCについて ${icon('right')}</a></section><section class="news-strip floating"><a class="news-label" href="/information/">${icon('bell')}Information</a><div class="news-list">${rows(S.news)}</div></section><section class="quick-links">${quick.map(([path,label,jp,color,type])=>`<a href="/${path}/" class="quick-link floating ${color}">${icon(type)}<div><strong>${label}</strong><small>${jp}</small></div><span class="arrow">${icon('right')}</span></a>`).join('')}</section><section class="section"><div class="section-heading"><h2>Our products.</h2><a class="text-link" href="/product/">すべての製品を見る ${icon('right')}</a></div>${cards(S.products)}${note}</section></div>`}
function products(){const filters=[['all','すべて'],['app','アプリケーション'],['web','Webサービス'],['project','開発プロジェクト']];return `${pageHero('Product','製品紹介')}<section class="section wrap"><div class="filters">${filters.map(([v,t])=>`<button class="filter ${v==='all'?'active':''}" data-filter="${v}" aria-pressed="${v==='all'}">${t}</button>`).join('')}</div><div id="product-results">${cards(S.products)}</div>${note}</section>`}
function information(){return `${pageHero('Information','TowaPCからのお知らせ')}<section class="section wrap"><div class="view-switch" role="group" aria-label="お知らせの表示形式"><button class="view-button active" data-news-view="list" aria-pressed="true">${icon('list')}リスト</button><button class="view-button" data-news-view="grid" aria-pressed="false">${icon('grid')}グリッド</button></div><div id="information-results" class="info-list floating">${rows(S.news)}</div>${note}</section>`}
function about(){const values=[['好奇心を大切に。','身近な疑問に目を向け、新しい可能性を探ります。','lavender'],['つくりながら、学ぶ。','まずは試して、少しずつ。小さな一歩を積み重ねます。','mint'],['一緒に、前へ。','異なる視点やアイデアから、次のものづくりが生まれます。','cream']];return `${pageHero('About','TowaPCについて')}<section class="section wrap"><div class="article floating about-summary"><h2>TowaPCについて</h2><p>${E(S.description)}</p><p>「もっと便利にできないか」「こんな仕組みがあったら」。そんな身近な問いを出発点に、学び、試し、つくることを大切にしています。</p><div class="about-links"><a class="soft-button" href="/cooperation/">協力関係 ${icon('right')}</a><a class="soft-button" href="/members/">メンバー ${icon('right')}</a><a class="soft-button" href="/contact/">お問い合わせ ${icon('right')}</a></div></div><div class="values">${values.map(([h,p,c])=>`<div class="value floating ${c}"><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></section>`}
function join(){const url=/^https?:\/\//.test(S.joinUrl)?S.joinUrl:'';const steps=[['興味を見つける','製品や取り組みを見て、気になるテーマを探してみてください。'],['アイデアを持ち寄る','経験の多さよりも、知りたい・つくりたいという気持ちを。'],['一歩を踏み出す','参加窓口の公開後に、詳しい参加方法をご案内します。']];return `${pageHero('Join','TowaPCに参加する')}<section class="section wrap join-section"><div class="join-box floating"><h2>あなたの「つくりたい」を、<br>ここから。</h2><p>プログラミング、デザイン、アイデア。<br>それぞれの得意や好奇心を持ち寄って、一緒に新しいものづくりをはじめませんか。</p>${url?`<a class="cta" href="${E(url)}" target="_blank" rel="noopener">参加について問い合わせる ${icon('right')}</a>`:'<span class="status">参加方法は、ただいま準備中です</span>'}</div><div class="values">${steps.map(([h,p])=>`<div class="value floating join-value"><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></section>`}
function directory(kind){const cooperation=kind==='cooperation',list=cooperation?S.partners:S.members,title=cooperation?'Cooperation':'Members',jp=cooperation?'協力関係にある団体・個人':'TowaPCのメンバー';return `${pageHero(title,jp)}<section class="section wrap"><div class="directory-grid">${list.length?list.map(i=>`<article class="directory-card floating">${img(i.image,i.name,'directory-image')}<div><span class="category">${E(i.role||'')}</span><h2>${E(i.name)}</h2><p>${E(i.description||'')}</p>${i.url?`<a class="text-link" href="${E(i.url)}" target="_blank" rel="noopener">Webサイト ${icon('right')}</a>`:''}</div></article>`).join(''):`<div class="empty-state floating">${icon(cooperation?'link':'people')}<p>${cooperation?'掲載する団体・個人':'メンバー情報'}を準備しています。</p><small>content-v2.jsから追加できます。</small></div>`}</div></section>`}
function contact(){const contacts=[['youtube','YouTube',S.socials.youtube],['x','X',S.socials.x],['discord','Discord',S.socials.discord]];return `${pageHero('Contact','お問い合わせ・公式リンク')}<section class="section wrap"><div class="contact-grid">${contacts.map(([type,label,url])=>url?`<a id="${type}" class="contact-card floating" href="${E(url)}" target="_blank" rel="noopener">${icon(type)}<div><h2>${label}</h2><p>公式ページを開く</p></div>${icon('right')}</a>`:`<div id="${type}" class="contact-card floating unavailable">${icon(type)}<div><h2>${label}</h2><p>URL準備中</p></div></div>`).join('')}<div class="contact-card floating">${icon('mail')}<div><h2>お問い合わせ</h2><p>${S.contactUrl?'お問い合わせページを開く':'窓口を準備しています'}</p></div>${S.contactUrl?`<a class="card-link" href="${E(S.contactUrl)}" target="_blank" rel="noopener">${icon('right')}</a>`:''}</div></div></section>`}
function detail(kind,id){if(!['product','information'].includes(kind))return missing();const isProduct=kind==='product',item=(isProduct?S.products:S.news).find(x=>x.id===id);if(!item)return missing();return `${pageHero(isProduct?'Product':'Information',isProduct?'製品紹介':'お知らせ')}<section class="section wrap"><article class="article floating">${isProduct?art(item):img(item.image,item.title,'article-image')}<span class="category">${isProduct?E(item.category):`${E(item.date)} · ${E(item.tag)}`}</span><h2>${E(isProduct?item.name:item.title)}</h2><p>${E(isProduct?item.description:item.body)}</p>${note}<a class="text-link" href="/${kind}/">${icon('left')} 一覧に戻る</a></article></section>`}
function missing(){return `${pageHero('Page not found','ページが見つかりませんでした')}<section class="section wrap"><a class="cta" href="/">ホームに戻る</a></section>`}
function headerNav(route){const items=[['','Home'],['product','Product'],['information','Information'],['about','About'],['join','Join']];return `<span class="nav-selection"></span>${items.map(([path,label])=>`<a href="/${path?`${path}/`:''}" data-route="${path}">${label}</a>`).join('')}`}
function render(){const parts=location.pathname.split('/').filter(Boolean),route=parts[0]||'',pages={'':home,product:products,information,about,join,cooperation:()=>directory('cooperation'),members:()=>directory('members'),contact};document.getElementById('main').innerHTML=parts.length>1?detail(route,parts[1]):(pages[route]||missing)();document.title=`TowaPC — ${routes.find(([p])=>p===`/${route}`)?.[1]||(route?'Page':'Home')}`;const nav=document.querySelector('.header nav');if(!nav.querySelector('[data-route]'))nav.innerHTML=headerNav(route);nav.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));document.querySelector('[data-footer-links]').innerHTML=routes.filter(([p])=>p!=='/contact').map(([p,t])=>`<a href="${p==='/'?'/':p+'/'}">${t}</a>`).join('');document.querySelector('[data-footer-contact]').innerHTML='<a href="/contact/#youtube">YouTube</a><a href="/contact/#x">X</a><a href="/contact/#discord">Discord</a><a href="/contact/">お問い合わせ</a>';nav.classList.remove('open');document.querySelector('.menu-button').setAttribute('aria-expanded','false');document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});document.getElementById('product-results').innerHTML=cards(S.products.filter(p=>b.dataset.filter==='all'||p.type===b.dataset.filter));reveal()}));document.querySelectorAll('[data-news-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-news-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});const results=document.getElementById('information-results');results.className=b.dataset.newsView==='list'?'info-list floating':'news-results';results.innerHTML=b.dataset.newsView==='list'?rows(S.news):newsCards(S.news);reveal()}));window.scrollTo({top:0,behavior:'instant'});reveal();requestAnimationFrame(positionSelection)}
document.querySelector('.menu-button').addEventListener('click',e=>{const open=document.querySelector('.header nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});document.querySelector('.back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||a.target)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;e.preventDefault();const next=u.pathname==='/'?'/':u.pathname.replace(/\/?$/,'/');if(location.pathname!==next)history.pushState(null,'',next+u.hash);render();if(u.hash)requestAnimationFrame(()=>document.querySelector(u.hash)?.scrollIntoView({behavior:'smooth'}))});
let observer;function reveal(){if(observer)observer.disconnect();if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const current=new IntersectionObserver(es=>es.forEach(entry=>{if(!entry.isIntersecting)return;const target=entry.target,delay=Number(target.dataset.revealDelay||0);target.classList.add('is-visible');target.animate([{opacity:0,transform:'translate3d(0,18px,0)'},{opacity:1,transform:'translate3d(0,0,0)'}],{duration:620,delay,easing:'cubic-bezier(.22,.8,.24,1)',fill:'none'});current.unobserve(target)}),{threshold:.08});observer=current;const items=[...document.querySelectorAll('.floating,.section-heading')];items.forEach((e,i)=>{e.classList.remove('is-visible');e.classList.add('reveal');e.dataset.revealDelay=String(i%4*55)});requestAnimationFrame(()=>{if(observer===current)items.forEach(e=>current.observe(e))})}
function positionSelection(){const nav=document.querySelector('.header nav'),selected=nav.querySelector(':scope>a.active,:scope>details.active-group>summary'),pill=nav.querySelector('.nav-selection');if(!selected||!nav.offsetWidth){pill.style.opacity='0';return}pill.style.opacity='1';pill.style.width=`${selected.offsetWidth}px`;pill.style.height=`${selected.offsetHeight}px`;pill.style.transform=`translate(${selected.offsetLeft}px,${selected.offsetTop}px)`;requestAnimationFrame(()=>nav.classList.add('nav-ready'))}
function migrate(){if(location.hash.startsWith('#/'))history.replaceState(null,'',location.hash.slice(1).replace(/\/?$/,'/'))}window.addEventListener('resize',positionSelection);window.addEventListener('popstate',()=>{migrate();render()});window.addEventListener('hashchange',()=>{migrate();render()});document.fonts.ready.then(positionSelection);migrate();render();
