const S=window.SITE;
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const E=escapeHtml;
const links=[['/','Home'],['/product','Product'],['/information','Information'],['/about','About'],['/join','Join']];
const paths={bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',about:'M12 8v.1M12 12v5M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',join:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M20 8v6M17 11h6',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.grid}"/></svg>`;
function art(p){return `<div class="product-art ${E(p.color)}"><div class="mock-window">${p.type==='app'?'<div class="dots"><i></i><i></i><i></i></div><div class="mock-content"><div class="mock-sidebar"></div><div class="mock-lines"><i></i><i></i><i></i></div></div>':icon(p.type==='web'?'join':'spark')}</div></div>`}
function cards(items){return `<div class="grid">${items.map(p=>`<a class="product" href="/product/${E(p.id)}">${art(p)}<div class="product-copy"><span class="category">${E(p.category)}</span><h3>${E(p.name)}</h3><p>${E(p.description)}</p><div class="product-bottom"><span>サンプルプロジェクト</span><span>詳しく見る ↗</span></div></div></a>`).join('')}</div>`}
function rows(items){return items.map(n=>`<a class="news-row" href="/information/${E(n.id)}"><time datetime="${E(n.date.replaceAll('.','-'))}">${E(n.date)}</time><span class="badge ${n.tag.toLowerCase()}">${E(n.tag)}</span><span class="news-title">${E(n.title)}</span><span class="arrow">↗</span></a>`).join('')}
function pageHero(title,jp){return `<section class="page-hero"><div class="wrap"><div class="breadcrumbs"><a href="/">Home</a> &nbsp; / &nbsp; ${E(title)}</div><h1>${E(title)}</h1><p>${E(jp)}</p></div></section>`}
const note='<p class="sample-note">※ 製品・お知らせの内容は、レイアウト確認用のサンプルです。</p>';
function home(){return `<section class="hero photo"><img class="hero-background" src="${E(S.hero)}" alt="夕焼けに染まる街並み" fetchpriority="high"><h1>${E(S.headline)}</h1></section><div class="wrap"><section class="intro"><h2>What’s “TowaPC”?</h2><p>${E(S.description)}</p><a class="text-link" href="/about">TowaPCについて <span>↗</span></a></section><section class="news-strip" aria-label="最新のお知らせ"><a class="news-label" href="/information">${icon('bell')}Information</a><div class="news-list">${rows(S.news)}</div></section><section class="quick-links" aria-label="ページへのリンク">${[['information','Information','お知らせ','pink','bell'],['product','Product','製品紹介','lavender','grid'],['about','About','TowaPCについて','mint','about'],['join','Join','TowaPCに参加する','cream','join']].map(([path,label,jp,color,i])=>`<a href="/${path}" class="quick-link ${color}">${icon(i)}<div><strong>${label}</strong><small>${jp}</small></div><span class="arrow">↗</span></a>`).join('')}</section><section class="section"><div class="section-heading"><div><h2>Our products.</h2></div><a class="text-link" href="/product">すべての製品を見る <span>↗</span></a></div>${cards(S.products)}${note}</section></div>`}
function products(){return `${pageHero('Product','製品紹介')}<section class="section wrap"><div class="filters" aria-label="製品のカテゴリ">${[['all','すべて'],['app','アプリケーション'],['web','Webサービス'],['project','開発プロジェクト']].map(([v,t])=>`<button class="filter ${v==='all'?'active':''}" data-filter="${v}" aria-pressed="${v==='all'}">${t}</button>`).join('')}</div><div id="product-results">${cards(S.products)}</div>${note}</section>`}
function information(){return `${pageHero('Information','TowaPCからのお知らせ')}<section class="section wrap"><div class="info-list">${rows(S.news)}</div>${note}</section>`}
function about(){return `${pageHero('About','TowaPCについて')}<section class="section wrap"><div class="article"><h2>TowaPCについて</h2><p>${E(S.description)}</p><p>「もっと便利にできないか」「こんな仕組みがあったら」。そんな身近な問いを出発点に、学び、試し、つくることを大切にしています。</p><p class="sample-note">※ 紹介文は仮の文章です。正式な活動内容に合わせて変更できます。</p></div><div class="values">${[['01','好奇心を大切に。','身近な疑問に目を向け、新しい可能性を探ります。','lavender'],['02','つくりながら、学ぶ。','まずは試して、少しずつ。小さな一歩を積み重ねます。','mint'],['03','一緒に、前へ。','異なる視点やアイデアから、次のものづくりが生まれます。','cream']].map(([n,h,p,c])=>`<div class="value ${c}"><span>${n}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></section>`}
function join(){const url=/^https?:\/\//.test(S.joinUrl)?S.joinUrl:'';return `${pageHero('Join','TowaPCに参加する')}<section class="section wrap"><div class="join-box"><h2>あなたの「つくりたい」を、<br>ここから。</h2><p>プログラミング、デザイン、アイデア。<br>それぞれの得意や好奇心を持ち寄って、<br>一緒に新しいものづくりをはじめませんか。</p>${url?`<a class="cta" href="${E(url)}" target="_blank" rel="noopener noreferrer">参加について問い合わせる ↗</a>`:'<span class="status">参加方法は、ただいま準備中です</span>'}</div><div class="values">${[['01','興味を見つける','製品や取り組みを見て、気になるテーマを探してみてください。'],['02','アイデアを持ち寄る','経験の多さよりも、知りたい・つくりたいという気持ちを。'],['03','一歩を踏み出す','参加窓口の公開後に、詳しい参加方法をご案内します。']].map(([n,h,p])=>`<div class="value" style="background:white"><span>${n}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></section>`}
function detail(kind,id){if(!['product','information'].includes(kind))return notFound();const isProduct=kind==='product',item=(isProduct?S.products:S.news).find(x=>x.id===id);if(!item)return notFound();return `${pageHero(isProduct?'Product':'Information',isProduct?'製品紹介':'お知らせ')}<section class="section wrap"><article class="article">${isProduct?art(item):`<span class="category">${E(item.date)} · ${E(item.tag)}</span>`}<h2>${E(isProduct?item.name:item.title)}</h2><p>${E(isProduct?item.description:item.body)}</p><p class="sample-note">この内容はレイアウト確認用のサンプルです。</p><a class="text-link" href="/${kind}">← ${isProduct?'製品一覧':'お知らせ一覧'}に戻る</a></article></section>`}
function notFound(){return `${pageHero('Page not found','ページが見つかりませんでした')}<section class="section wrap"><a class="cta" href="/">ホームに戻る →</a></section>`}
function render(){const path=location.pathname,parts=path.split('/').filter(Boolean),route=parts[0]||'';document.getElementById('main').innerHTML=parts.length>1?detail(route,parts[1]):({'':home,product:products,information,about,join}[route]||notFound)();document.title=`TowaPC — ${links.find(([p])=>p==='/'+route)?.[1]||'Page'}`;document.querySelectorAll('header nav,footer nav').forEach(nav=>{if(!nav.querySelector('a'))nav.innerHTML=(nav.closest('header')?'<span class="nav-selection" aria-hidden="true"></span>':'')+links.map(([p,t])=>`<a href="${p==='/'?p:p+'/'}">${t}</a>`).join('');nav.querySelectorAll('a').forEach(a=>{const active=a.pathname.replace(/\/$/,'')===('/'+route).replace(/\/$/,'');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})});document.querySelector('.header nav').classList.remove('open');document.querySelector('.menu-button').setAttribute('aria-expanded','false');document.querySelector('.menu-button').setAttribute('aria-label','メニューを開く');document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});document.getElementById('product-results').innerHTML=cards(S.products.filter(p=>b.dataset.filter==='all'||p.type===b.dataset.filter))}));window.scrollTo({top:0,behavior:'instant'});animateSections();requestAnimationFrame(positionSelection)}
document.querySelectorAll('.custom-logo').forEach(img=>{img.onerror=()=>{img.style.visibility='hidden'};if(img.getAttribute('src')!==S.logo)img.src=S.logo});
document.querySelector('.menu-button').addEventListener('click',e=>{const open=document.querySelector('.header nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open));e.currentTarget.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');requestAnimationFrame(positionSelection)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.header nav').classList.remove('open');document.querySelector('.menu-button').setAttribute('aria-expanded','false')}});
document.querySelector('.back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));

let revealObserver;
function animateSections(){
  if(revealObserver)revealObserver.disconnect();
  if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:0.08});
  document.querySelectorAll('.intro,.news-strip,.quick-links,.section-heading,.product,.article,.value,.join-box').forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--reveal-delay',((el.matches('.product,.value')?i%3:0)*70)+'ms');revealObserver.observe(el)});
}

function positionSelection(){const nav=document.querySelector('.header nav'),active=nav.querySelector('a.active'),pill=nav.querySelector('.nav-selection');if(!active||!nav.offsetWidth){if(pill)pill.style.opacity='0';return}pill.style.opacity='1';pill.style.width=active.offsetWidth+'px';pill.style.height=active.offsetHeight+'px';pill.style.transform='translate('+active.offsetLeft+'px,'+active.offsetTop+'px)';requestAnimationFrame(()=>nav.classList.add('nav-ready'))}
window.addEventListener('resize',positionSelection);document.fonts.ready.then(positionSelection);
function migrateHash(){if(location.hash.startsWith('#/'))history.replaceState(null,'',location.hash.slice(1).replace(/\/?$/,'/'))}
window.addEventListener('popstate',()=>{migrateHash();render()});window.addEventListener('hashchange',()=>{migrateHash();render()});
document.addEventListener('click',event=>{const a=event.target.closest('a');if(!a||event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||a.target||a.hasAttribute('download'))return;const url=new URL(a.href,location.href);if(url.origin!==location.origin||url.hash||!url.pathname.startsWith('/'))return;event.preventDefault();const next=url.pathname==='/'?'/':url.pathname.replace(/\/?$/,'/');if(location.pathname!==next)history.pushState(null,'',next+url.search);render()});
migrateHash();render();
